language: python
python:
- '2.7'
cache: pip
env:
    matrix:
        - DJANGO="Django<1.10,>=1.9"
        - DJANGO="Django<1.9,>=1.8"
        - DJANGO="Django<1.8,>=1.7"
install:
    - pip install $DJANGO
    - pip install -r noodles_tests/requirements.txt
sudo: false
